### ISSUE TITLE
8.X Support?

### ISSUE THREAD

**Issue by CSorel-Catalyte** [Data8/DataverseClient#24]
I am attempting to authenticate to an on premise Dynamics 365 instance at version 8.2.11.13 The instance is configured for IFD/Claims authentication against ADFS in Windows Server 2012. I created a .net6 console app test harness to confirm functionality. Executing the following code results in Access Denied errors on the execute and create actions. This suggests that it is authenticating but does not have sufficient claims to act. The user I am logging in as is a System Admin. I'm looking to see if the configuration is supported (8.x, ADFS 2012) and if my approach is correct.

```

       static void Main(string[] args)
        {
            Console.WriteLine("Starting Authentication Test");

            CRMConnectionConfig _crmConnectionConfig = new CRMConnectionConfig()
            {
                DiscoveryServiceAddress = "https://redacted/XRMServices/2011/Discovery.svc",
                OrganizationServiceAddress = "https://redacted/XRMServices/2011/Organization.svc",
                Domain = "redacted.com",
                OrganizationUniqueName = "redacted",
                UserName = "redacted@redacted.com",
                Password = "redacted"
            };


            OnPremiseClient onPremiseClient = CRMAuthHelper.GetAuthenticatedOnPremiseClient(_crmConnectionConfig);

            try
            {
                Console.WriteLine("Testing whoamirequest");
                Guid userid = ((WhoAmIResponse)onPremiseClient.Execute(new WhoAmIRequest())).UserId;
                Entity systemUser = onPremiseClient.Retrieve("systemuser", userid,
                    new ColumnSet(new string[] { "firstname", "lastname" }));
                Console.WriteLine("Logged on user is {0} {1}.", systemUser.GetAttributeValue<string>("firstname"), systemUser.GetAttributeValue<string>("lastname"));

            }
            catch(Exception ex)
            {
                Console.WriteLine("Whoami failed: " + ex.Message + " " + ex.StackTrace);
            }
            try
            {
                Console.WriteLine("Testing Contact Create");
                var entity = new Entity("contact")
                {
                    ["firstname"] = "authtest",
                    ["lastname"] = "testuser",
                };

                entity.Id = onPremiseClient.Create(entity);
                Console.WriteLine("Contact Create Succeeded: ID: " + entity.Id);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Contact Create failed: " + ex.Message + " " + ex.StackTrace);
            }

            Console.WriteLine("Press any key to exit");
            Console.ReadLine();
        }
    }

```
The helper function to get the OnPremiseClient is:

```
public static OnPremiseClient GetAuthenticatedOnPremiseClient(CRMConnectionConfig config)
        {
            string username = config.UserName;
            if(! username.Contains("@") && !username.Contains("\\"))
            {
                username = $@"{config.Domain}\{config.UserName}";
            }
            var svc = new OnPremiseClient(config.OrganizationServiceAddress, username, config.Password);
            return svc;
        }
```

The output from the test harness is:

```
Starting Authentication Test
Testing whoamirequest
Whoami failed: Access is denied.    at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.Execute(OrganizationRequest )
   at Data8.PowerPlatform.Dataverse.Client.OnPremiseClient.Execute(OrganizationRequest request)
   at V6AuthTest.Program.Main(String[] args) in C:\repo\CRMApiAuthTest\V6AuthTest\Program.cs:line 35

Testing Contact Create
Contact Create failed: Access is denied.    at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.Create(Entity )
   at Data8.PowerPlatform.Dataverse.Client.OnPremiseClient.Create(Entity entity)
   at V6AuthTest.Program.Main(String[] args) in C:\repo\CRMApiAuthTest\V6AuthTest\Program.cs:line 54
Press any key to exit
```

**Comment by MarkMpn** [comment]
This combination should work, the error looks like it’s ADFS related. Please check the article at https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/adfs-2-error-access-is-denied for some troubleshooting steps.

**Comment by CSorel-Catalyte** [comment]
Thanks for the confirmation on the setup. I'll take a look at the article.
