### ISSUE TITLE
Exception while authenticating on linux host

### ISSUE THREAD

**Issue by nimasfl** [Data8/DataverseClient#30]
It works on windows platform perfectly but when I deployed it on linux server using docker image `mcr.microsoft.com/dotnet/aspnet:7.0` which uses `Debian 11 Bullseye` it requires to install gss-ntlmssp package (as documentation also said).
I installed it on the image but when I want to make use of the service the error with bellow stacktrace happens:
```Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Security.SafeDeleteNegoContext.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Dispose()
   at System.Net.Security.SafeDeleteNegoContext..ctor(SafeFreeNegoCredentials credential, String targetName)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, ChannelBinding channelBinding, String targetName, ContextFlagsPal inFlags, ReadOnlySpan`1 incomingBlob, Byte[]& resultBuffer, ContextFlagsPal& outFlags)
   at System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(SafeFreeCredentials& credentialsHandle, SafeDeleteContext& securityContext, String spn, ContextFlagsPal requestedContextFlags, ReadOnlySpan`1 incomingBlob, ChannelBinding channelBinding, Byte[]& resultBlob, Int32& resultBlobLength, ContextFlagsPal& contextFlags)
   at System.Net.NTAuthentication.GetOutgoingBlob(ReadOnlySpan`1 incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.Security.NegotiateAuthentication.GetOutgoingBlob(ReadOnlySpan`1 incomingBlob, NegotiateAuthenticationStatusCode& statusCode)
   at Data8.PowerPlatform.Dataverse.Client.ADAuthClient.Authenticate()
   at Data8.PowerPlatform.Dataverse.Client.ADAuthClient.Execute(OrganizationRequest request)
   at Data8.PowerPlatform.Dataverse.Client.OnPremiseClient.Execute(OrganizationRequest request)
   at Ahanonline.Common.DynamicsClient.DynamicsClientService.SetStatus(SetStatusParam param) in /src/Common/DynamicsClient/DynamicsClientService.cs:line 112
   at Ahanonline.Services.OnlineQuotes.OnlineQuotesService.UpdateStatus(UpdateOnlineQuoteStatusRequest body, Requester requester) in /src/Services/OnlineQuotes/OnlineQuotesService.cs:line 48
   at Ahanonline.App.Controllers.OnlineQuotesController.UpdateStatus(UpdateOnlineQuoteStatusRequest dto, Requester requester) in /src/App/Controllers/OnlineQuotesController.cs:line 30
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ahanonline.Common.Exceptions.Middlewares.AppExceptionHandlerMiddleware.Invoke(HttpContext context) in /src/Common/Exceptions/Middlewares/AppExceptionHandlerMiddleware.cs:line 24
```

I added an implementation on my github repository. The requirements is that you have an on-premise dynamics 365 to test it.

https://github.com/nimasfl/dotnet7-dynamics-test

**Comment by MarkMpn** [comment]
Thanks for the stack trace - my best guess from this is that it's not picking up an SPN from the server's WSDL. The `System.Net.NTAuthentication` class appears to require this in the Linux implementation but not in the Windows implementation.

Are you able to share the WSDL from your CRM server in case there's somewhere else the code can pick this up from please? It comes in multiple parts from each of the following URLs:

https://crmserver.contoso.com/OrgName/XRMServices/2011/Organization.svc?wsdl
https://crmserver.contoso.com/OrgName/XRMServices/2011/Organization.svc?wsdl=wsdl0

**Comment by nimasfl** [comment]
Here is our WSDL URL:
https://xrmtest.ahanoffline.ir/test/XRMServices/2011/Organization.svc?wsdl
You can use the following credentials if you need to login:
username: a.Salarpoor
password: Aa123456

**Comment by MarkMpn** [comment]
Thanks for these details. It does appear that your WSDL is not advertising the SPN for the https endpoint.

It is advertising both an http and an https endpoint. The http endpoint definition contains an SPN, but the https endpoint does not.

I'm not sure if having both an http and an https endpoint is supported. I'd suggest removing the http binding in IIS to leave only the https binding, and ensure the https option is ticked in Deployment Manager - select the main "Dynamics 365" node in the left hand tree, click Properties in the right-hand Actions pane, go to the Web Address tab and check the Binding Type setting at the top.

**Comment by nimasfl** [comment]
I appreciate your help but it didn't work with the solution you provided in the last comment.
I disabled HTTP binding in IIS and configured dynamics to listen on HTTPS in the Deployment manager.

![image](https://user-images.githubusercontent.com/45030953/208292495-3bd90011-2494-4cf9-8279-b3985512c8da.png)

I  even added a new SPN "HTTP/xrmtest2.ahanoffline.ir" but the error kept happening.

Here is my organization service WSDL info:
![image](https://user-images.githubusercontent.com/45030953/208292533-fd66e60a-f600-4cfa-a42c-e72795ac3bd1.png)
My guess is organization service is still using the previous SPN but I couldn't find a way to change that.

Is there any way I  can use this package using HTTP or anything that you recommend?

**Comment by MarkMpn** [comment]
The WSDL is still showing the http url, so either you still have an http binding configured or Dynamics is still picking up the old binding for some reason. Can you start off running iisreset to try to get Dynamics to pick up the new settings?

**Comment by nimasfl** [comment]
You're right. my screenshot was from the time when I added back HTTP binding.
This is my organization service WSDL after removing HTTP binding:

![image](https://user-images.githubusercontent.com/45030953/208357212-0f445bfc-a821-499f-b450-4d3df4a2abbf.png)

And this is my SPN list on the server:

![image](https://user-images.githubusercontent.com/45030953/208357679-ac54ab00-e963-4b6d-9a0a-cb7bfc6be441.png)

**Comment by MarkMpn** [comment]
Can you check:

1. What identity the CRM app pool is running under?
2. What authentication providers are enabled (in IIS Manager, select the Microsoft Dynamics CRM application, open the Authentication section, select Windows Authentication and click Providers in the right hand pane)

**Comment by nimasfl** [comment]
The problem was caused because of CrmAppPool running with a Built-in Windows user called "NetworkService". I've changed it to a domain user and everything worked correctly.
If anyone is facing the same issue just ignore any of my previous comments. Just change the CrmAppPool user to a domain username and it works just fine. It is even working with both HTTP and HTTPS binding at the same time.

@MarkMpn I really appreciate your help in walking me down to solve this issue.
