### ISSUE TITLE
Cannot have two operations in the same contract with the same name

### ISSUE THREAD

**Issue by csobrien** [Data8/DataverseClient#38]
We've been using the 2.0.2 version of the package along with the 0.6.6 version of Microsoft.PowerPlatform.Dataverse.Client and it has been working fine in our environment.

Yesterday we spun up a new project using the latest of both (2.4.0 and 1.1.14 respectively) and are now getting the following error in the constructor of the OnPremiseClient:

Cannot have two operations in the same contract with the same name, methods Associate and AssociateAsync in type Microsoft.PowerPlatform.Dataverse.Client.IOrganizationServiceAsync2 violate this rule. You can change the name of one of the operations by changing the method name or by using the Name property of OperationContractAttribute.

Stack trace:
   at System.ServiceModel.Description.TypeLoader.CreateOperationDescription(ContractDescription contractDescription, MethodInfo methodInfo, MessageDirection direction, ContractReflectionInfo reflectionInfo, ContractDescription declaringContract) in /_/src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs:line 895
   at System.ServiceModel.Description.TypeLoader.CreateOperationDescriptions(ContractDescription contractDescription, ContractReflectionInfo reflectionInfo, Type contractToGetMethodsFrom, ContractDescription declaringContract, MessageDirection direction) in /_/src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs:line 703
   at System.ServiceModel.Description.TypeLoader.CreateContractDescription(ServiceContractAttribute contractAttr, Type contractType, Type serviceType, ContractReflectionInfo& reflectionInfo, Object serviceImplementation) in /_/src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs:line 810
   at System.ServiceModel.Description.TypeLoader.LoadContractDescriptionHelper(Type contractType, Type serviceType, Object serviceImplementation) in /_/src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs:line 78
   at System.ServiceModel.Description.TypeLoader.LoadContractDescription(Type contractType) in /_/src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs:line 160
   at System.ServiceModel.Description.ContractDescription.GetContract(Type contractType) in /_/src/System.Private.ServiceModel/src/System/ServiceModel/Description/ContractDescription.cs:line 141
   at Data8.PowerPlatform.Dataverse.Client.ClaimsBasedAuthClient.CreateServiceEndpoint(String url, String issuerEndpoint)
   at Data8.PowerPlatform.Dataverse.Client.ClaimsBasedAuthClient..ctor(String url, String issuerEndpoint)
   at Data8.PowerPlatform.Dataverse.Client.OnPremiseClient.ConnectFederated(String url, ClientCredentials credentials, List`1 policies)
   at Data8.PowerPlatform.Dataverse.Client.OnPremiseClient.GetInnerService()
   at Data8.PowerPlatform.Dataverse.Client.OnPremiseClient..ctor(String url, ClientCredentials credentials)
   at Data8.PowerPlatform.Dataverse.Client.OnPremiseClient..ctor(String url, String username, String password)
   at UserQuery.Main(), line 2

**Comment by csobrien** [comment]
Confirmed this fixes it for us.  Thanks for the quick turnaround!
