### ISSUE TITLE
google cloud to on premise error The security context token is expired or is not valid

### ISSUE THREAD

**Issue by menasheAtias** [Data8/DataverseClient#43]
Hi
We have a service that creates a record in the CRM, from the development machine running through SWAGGER it works great without errors, we uploaded it to google cloud run from there the service goes to CRM which is inside a virtual machine in the cloud, we get the following error when creating record 
ExceptionHandlingMiddleware default Error ex:System.ServiceModel.FaultException: The security context token is expired or is not valid. The message was not processed.
at Data8.PowerPlatform.Dataverse.Client.ADAuthClient.Execute(OrganizationRequest request)
at Data8.PowerPlatform.Dataverse.Client.ADAuthClient.Create(Entity entity)
at Data8.PowerPlatform.Dataverse.Client.OnPremiseClient.Create(Entity entity)
, sometimes it works without error ,but most of the times it doesn't works and returns the error
We saw that it could be a time zone problem so we compared the time zone in the service to the CRM but  It didn't help, do you have any idea what the solution could be?

**Comment by NickGrava2** [comment]
Have you solved the problem?
